{% set name = "rosdep" %}
{% set version = "0.18.0" %}
{% set sha256 = "a7a89f91baa7d6e0db46c936c91a0d390bdcc023dfaa004307ddbd06fe4e97db" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/seanyen/rosdep.git
  git_rev: conda

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - rosdep = rosdep2.main:rosdep_main
    - rosdep-source = rosdep2.install:install_main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - catkin_pkg >=0.4.0
    - rospkg >=1.1.8
    - rosdistro >=0.7.0
    - pyyaml >=3.1

test:
  commands:
    - rosdep --help

about:
  home: http://wiki.ros.org/rosdep
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'ROS multi-package manager system dependency tool'
  dev_url: https://github.com/ros-infrastructure/rosdep

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
