{% set name = "rosdep" %}
{% set version = "0.21.0" %}
{% set sha256 = "36855f69398f6d6973dbdaa8f50204f9d7cbdfecf9fb74df6aae2c0510451a18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ros-infrastructure/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - add-robostack.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - rosdep = rosdep2.main:rosdep_main
    - rosdep-source = rosdep2.install:install_main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - catkin_pkg >=0.4.0
    - rospkg >=1.3.0
    - rosdistro >=0.8.3
    - pyyaml >=3.1

test:
  commands:
    - rosdep --help

about:
  home: http://wiki.ros.org/rosdep
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ROS multi-package manager system dependency tool
  dev_url: https://github.com/ros-infrastructure/rosdep

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
